name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup Emacs
      uses: purcell/setup-emacs@master
      with:
        version: snapshot

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
         node-version: '12.x'

    - name: Build
      run: |
        make install
        make compile
        
    - name: Test Emacs startup
      run: |
        emacs --kill
        
    - name: Clean
      run: |
        make clean
